#ifndef MINIVCS_EC_H
#define MINIVCS_EC_H

#define ERROR_SUCCESS 0
#define ERROR_SYSTEM 1
#define ERROR_NOTFOUND 2
#define ERROR_CRYPTO 3
#define ERROR_MODE 4
#define ERROR_CONFIG 5

#endif //MINIVCS_EC_H
